### PR TITLE
Fix migration

### PR DESCRIPTION
**Pull request by sharwell**
* Allow the solution to open in both Visual Studio 2015 and Visual Studio 2017
* Allow the solution to build in both Visual Studio 2015 and Visual Studio 2017
* Only deploy the Visual Studio 2015 extension when building inside Visual Studio 2015
* Only deploy the Visual Studio 2017 extension when building inside Visual Studio 2017

### CODE REVIEW

**Comment by justcla** [comment]
Nice fixes Sam.

**Comment by rionmonster** [comment]
Awesome @sharwell and @justcla! I really appreciate this and hopefully it eases some of the development-related issues that I have been running into.

**Comment by rionmonster** [comment]
One question, after pulling down this branch. I'm able to open both projects (VS2015 and VS2017) within Visual Studio 2015, however I can only open VS2017 within Visual Studio 2017. 

Is that correct? Or is this simply related to the "forced conversion" issue that was occurring earlier?

**Comment by sharwell** [comment]
> however I can only open VS2017 within Visual Studio 2017.

This isn't what I expected. I'll take a look.

**Comment by sharwell** [comment]
@rionmonster Both projects load for me within Visual Studio 2017. Maybe you have to restore NuGet packages before it will load?

**Comment by rionmonster** [comment]
The NuGet restore seemed to resolve the issue. Thanks again for the PR and the suggestion @sharwell  :)

**Pull request merged**
